name: sample
description: "Transport Management App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter 
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.0
  firebase_auth_web: ^5.8.13
  crypto: ^3.0.3
  intl: ^0.18.1
  firebase_admin: ^0.3.0
  googleapis_auth: ^1.3.0
  http: ^1.1.0
  cloud_firestore: ^4.17.5
  bcrypt: ^1.1.3
  shared_preferences: ^2.2.2
  flutter_typeahead: ^4.1.2
  provider: ^6.0.5 
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  
  

flutter:
  uses-material-design: true
