// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9Qem7vTeoAtIknMKx1nIXJi3wY_6shM',
    appId: '1:335395601302:web:a27da3b156be6ede93fbb7',
    messagingSenderId: '335395601302',
    projectId: 'app-backend-6477f',
    authDomain: 'app-backend-6477f.firebaseapp.com',
    storageBucket: 'app-backend-6477f.firebasestorage.app',
    measurementId: 'G-K1XZLCGWHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUFai121rMEl5A-DfYQXxSo8wuZelgPc',
    appId: '1:335395601302:android:593a54b24916997093fbb7',
    messagingSenderId: '335395601302',
    projectId: 'app-backend-6477f',
    storageBucket: 'app-backend-6477f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5owxpIEpR9C8s1MQ7fffoaPbHC1U-ho',
    appId: '1:335395601302:ios:4bc59f6b0920475d93fbb7',
    messagingSenderId: '335395601302',
    projectId: 'app-backend-6477f',
    storageBucket: 'app-backend-6477f.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5owxpIEpR9C8s1MQ7fffoaPbHC1U-ho',
    appId: '1:335395601302:ios:4bc59f6b0920475d93fbb7',
    messagingSenderId: '335395601302',
    projectId: 'app-backend-6477f',
    storageBucket: 'app-backend-6477f.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9Qem7vTeoAtIknMKx1nIXJi3wY_6shM',
    appId: '1:335395601302:web:71f9185831a8119b93fbb7',
    messagingSenderId: '335395601302',
    projectId: 'app-backend-6477f',
    authDomain: 'app-backend-6477f.firebaseapp.com',
    storageBucket: 'app-backend-6477f.firebasestorage.app',
    measurementId: 'G-J6FEKC1CQD',
  );
}